service: signup-post-confirmation
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: production
  region: eu-central-1
  memorySize: 128
  architecture: arm64
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 
            - "ses:SendEmail"
            - "ses:SendRawEmail"
          Resource: '*'
functions:
  app:
    handler: dist/lambda.handler